// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhlxoypsnlraplpifrfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobHhveXBzbmxyYXBscGlmcmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTI1NjQsImV4cCI6MjA2MjM2ODU2NH0.IS96VgQ6uZYVQh3ManQVTc_lpBK4B3NK1UBEaPiiE3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);